# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - 1
  - nightly

notifications:
  email: false

# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("HierarchicalHotNet"); Pkg.test("HierarchicalHotNet"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  #- julia -e 'cd(Pkg.dir("HierarchicalHotNet")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg, HierarchicalHotNet; cd(joinpath(dirname(pathof(HierarchicalHotNet)), "..")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
